services:
  - type: web
    name: book-recommendation-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: free
    autoDeploy: true
